name: Testing PRs

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node.js env
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2

      - name: Install deps
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
