export const dict = {
  en: {
    lobby: 'Lobby',
    copyLink: 'Copy invitation link',
    lobbyTeamName: 'Team name',
    myName: 'My name',
    myIcon: 'My icon',
    edit: 'Edit',
    teammates: 'Teammates',
    iAmReady: 'I am ready for game!',
    waitTeam: 'Wait for other teammates...',
    startGame: 'Start game',
    submit: 'Submit',
    ready: 'Ready',
    notReady: 'Not ready',
  },
  ru: {
    lobby: 'Холл',
    copyLink: 'Копировать ссылку на игру',
    lobbyTeamName: 'Название команды',
    myName: 'Мое имя',
    myIcon: 'Моя иконка',
    edit: 'Изменить',
    teammates: 'Коллеги',
    iAmReady: 'Готов играть!',
    waitTeam: 'Ждем остальных участников...',
    startGame: 'Начать игру',
    submit: 'Отправить',
    ready: 'Готов',
    notReady: 'Не готов',
  }
}